use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let schemas_dir = manifest_dir.join("../../schemas");
    let schemas_dir = schemas_dir
        .canonicalize()
        .expect("schemas/ directory not found");
    let config_schemas_dir = schemas_dir.join("config");
    let vexilc = env::var("VEXILC_PATH").unwrap_or_else(|_| "vexilc".to_string());

    let mut schema_files = Vec::new();
    collect_vexil_files(&config_schemas_dir, &mut schema_files);

    for schema in &schema_files {
        let status = Command::new(&vexilc)
            .arg("build")
            .arg(schema)
            .arg("--include")
            .arg(&schemas_dir)
            .arg("--output")
            .arg(&out_dir)
            .arg("--target")
            .arg("rust")
            .status()
            .unwrap_or_else(|e| panic!("failed to run vexilc: {e}"));

        if !status.success() {
            panic!("vexilc build failed for {}", schema.display());
        }
    }

    write_mod_rs(&out_dir);

    println!("cargo::rerun-if-changed={}", config_schemas_dir.display());
    for schema in &schema_files {
        println!("cargo::rerun-if-changed={}", schema.display());
    }
}

fn collect_vexil_files(dir: &Path, files: &mut Vec<PathBuf>) {
    if !dir.exists() {
        return;
    }
    for entry in fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_vexil_files(&path, files);
        } else if path.extension().is_some_and(|e| e == "vexil") {
            files.push(path);
        }
    }
}

const DAEMON_STUB: &str = r#"// Stub — vexilc not run.
#[derive(Debug, Clone, PartialEq)]
pub struct DaemonConfig {
    pub socket_path: Option<String>,
    pub max_sessions: u32,
    pub default_tier: String,
    pub scrollback_lines: u32,
    pub log_level: String,
    pub persist_dir: Option<String>,
    pub persist_interval_secs: u32,
}
impl Default for DaemonConfig {
    fn default() -> Self {
        Self {
            socket_path: None,
            max_sessions: 64,
            default_tier: "Bare".to_string(),
            scrollback_lines: 10000,
            log_level: "info".to_string(),
            persist_dir: None,
            persist_interval_secs: 30,
        }
    }
}
"#;

const USER_STUB: &str = r#"// Stub — vexilc not run.
#[derive(Debug, Clone, PartialEq)]
pub struct UserConfig {
    pub edit_mode: String,
    pub theme: Option<String>,
    pub shell: Option<String>,
    pub startup_commands: Vec<String>,
}
impl Default for UserConfig {
    fn default() -> Self {
        Self {
            edit_mode: "emacs".to_string(),
            theme: None,
            shell: None,
            startup_commands: vec![],
        }
    }
}
"#;

fn write_mod_rs(out_dir: &Path) {
    let malt_dir = out_dir.join("malt");
    if !malt_dir.exists() {
        // vexilc not available — write stub mod.rs files so the crate compiles.
        fs::create_dir_all(&malt_dir).unwrap();
        let config_dir = malt_dir.join("config");
        fs::create_dir_all(&config_dir).unwrap();

        let daemon_dir = config_dir.join("daemon");
        fs::create_dir_all(&daemon_dir).unwrap();
        fs::write(daemon_dir.join("mod.rs"), DAEMON_STUB).unwrap();

        let user_dir = config_dir.join("user");
        fs::create_dir_all(&user_dir).unwrap();
        fs::write(user_dir.join("mod.rs"), USER_STUB).unwrap();

        fs::write(
            config_dir.join("mod.rs"),
            "// Generated by malt-config build.rs. DO NOT EDIT.\n\npub mod daemon;\npub mod user;\n",
        )
        .unwrap();

        fs::write(
            malt_dir.join("mod.rs"),
            "// Generated by malt-config build.rs. DO NOT EDIT.\n\npub mod config;\n",
        )
        .unwrap();

        fs::write(
            out_dir.join("mod.rs"),
            "// Generated by malt-config build.rs. DO NOT EDIT.\n\npub mod malt;\n",
        )
        .unwrap();

        return;
    }

    // vexilc ran — walk generated output and build mod.rs hierarchy.
    let config_dir = malt_dir.join("config");
    let mut config_mods = Vec::new();

    if let Ok(entries) = fs::read_dir(&config_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file()
                && path.extension().is_some_and(|e| e == "rs")
                && path.file_stem().is_some_and(|s| s != "mod")
            {
                if let Some(name) = path.file_stem() {
                    config_mods.push(name.to_string_lossy().to_string());
                }
            } else if path.is_dir() && path.join("mod.rs").exists() {
                if let Some(name) = path.file_name() {
                    config_mods.push(name.to_string_lossy().to_string());
                }
            }
        }
    }
    config_mods.sort();

    let mut cc = String::from("// Generated by malt-config build.rs. DO NOT EDIT.\n\n");
    for m in &config_mods {
        cc.push_str(&format!("pub mod {m};\n"));
    }
    fs::write(config_dir.join("mod.rs"), &cc).unwrap();

    fs::write(
        malt_dir.join("mod.rs"),
        "// Generated by malt-config build.rs. DO NOT EDIT.\n\npub mod config;\n",
    )
    .unwrap();

    fs::write(
        out_dir.join("mod.rs"),
        "// Generated by malt-config build.rs. DO NOT EDIT.\n\npub mod malt;\n",
    )
    .unwrap();
}
