use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let schemas_dir = manifest_dir.join("../../schemas");
    let schemas_dir = schemas_dir
        .canonicalize()
        .expect("schemas/ directory not found");
    let vexilc = env::var("VEXILC_PATH").unwrap_or_else(|_| "vexilc".to_string());

    let mut schema_files = Vec::new();
    collect_vexil_files(&schemas_dir, &mut schema_files);

    for schema in &schema_files {
        let status = Command::new(&vexilc)
            .arg("build")
            .arg(schema)
            .arg("--include")
            .arg(&schemas_dir)
            .arg("--output")
            .arg(&out_dir)
            .arg("--target")
            .arg("rust")
            .status()
            .unwrap_or_else(|e| panic!("failed to run vexilc: {e}"));

        if !status.success() {
            panic!("vexilc build failed for {}", schema.display());
        }
    }

    write_mod_rs(&out_dir);

    println!("cargo::rerun-if-changed={}", schemas_dir.display());
    for schema in &schema_files {
        println!("cargo::rerun-if-changed={}", schema.display());
    }
}

fn collect_vexil_files(dir: &Path, files: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_vexil_files(&path, files);
        } else if path.extension().is_some_and(|e| e == "vexil") {
            files.push(path);
        }
    }
}

fn write_mod_rs(out_dir: &Path) {
    let malt_dir = out_dir.join("malt");
    let mut modules = Vec::new();

    if let Ok(entries) = fs::read_dir(&malt_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file()
                && path.extension().is_some_and(|e| e == "rs")
                && path.file_stem().is_some_and(|s| s != "mod")
            {
                if let Some(name) = path.file_stem() {
                    modules.push(name.to_string_lossy().to_string());
                }
            } else if path.is_dir() && path.join("mod.rs").exists() {
                if let Some(name) = path.file_name() {
                    modules.push(name.to_string_lossy().to_string());
                }
            }
        }
    }
    modules.sort();

    let mut content = String::from("// Generated by malt-protocol build.rs. DO NOT EDIT.\n\n");
    for m in &modules {
        content.push_str(&format!("pub mod {m};\n"));
    }
    fs::write(malt_dir.join("mod.rs"), &content).unwrap();

    // Handle persist/ subdirectory
    let persist_dir = malt_dir.join("persist");
    if persist_dir.is_dir() {
        let mut persist_mods = Vec::new();
        if let Ok(entries) = fs::read_dir(&persist_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file()
                    && path.extension().is_some_and(|e| e == "rs")
                    && path.file_stem().is_some_and(|s| s != "mod")
                {
                    if let Some(name) = path.file_stem() {
                        persist_mods.push(name.to_string_lossy().to_string());
                    }
                }
            }
        }
        persist_mods.sort();

        let mut pc = String::from("// Generated by malt-protocol build.rs. DO NOT EDIT.\n\n");
        for m in &persist_mods {
            pc.push_str(&format!("pub mod {m};\n"));
        }
        fs::write(persist_dir.join("mod.rs"), &pc).unwrap();
    }

    // Root mod.rs
    fs::write(
        out_dir.join("mod.rs"),
        "// Generated by malt-protocol build.rs. DO NOT EDIT.\n\npub mod malt;\n",
    )
    .unwrap();
}
